### ISSUE TITLE
FirebaseError: from DataCite API: Not-found. The resource is not found e.g. it fetching a DOI/Repository/Member ...

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/hakai-metadata-entry-form#2]
Sentry Issue: [CIOOS-METADATA-ENTRY-FORM-5W](https://hakai-institute.sentry.io/issues/5599343014/?referrer=github_integration)

```
FirebaseError: from DataCite API: Not-found. The resource is not found e.g. it fetching a DOI/Repository/Member details.
  at FirebaseError: from DataCite API: Not-found. The resource is not found e.g. it fetching a DOI (/Repository/Member details.)
```

Looks like creating a new record and submitting it to the hakai or cioos form created this error. Plus is seems like new records aren't generating a new issue within the repo https://github.com/HakaiInstitute/metadata-review

**Comment by JessyBarrette** [comment]
@fostermh any idea what's going on?

**Comment by JessyBarrette** [comment]
@timvdstap

**Comment by fostermh** [comment]
turns out the code did not handle the very command case of submitting a record without a doi... whoops. I adjusted the code to not attempt to update the draft doi if there isn't one set.
